swagger: "2.0"
info:
  version: "0.0.1"
  title: Hello World App
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /swagger:
    x-swagger-pipe: swagger_raw

  /resources:
    x-swagger-router-controller: resources
    get:
      operationId: getResources
      responses:
        default:
          description: Error
          schema:
            $ref: "#/definitions/Generic"
    post:
      operationId: addResource
      parameters:
        - name: resource
          in: body
          required: true
          schema:
            $ref: '#/definitions/Resource'
      responses:
        default:
          description: Error
          schema:
            $ref: "#/definitions/Generic"

  /resources/{resourceId}/approve/{isApproved}:
    x-swagger-router-controller: resources
    get:
      operationId: approveResource
      parameters:
        - name: resourceId
          in: path
          required: true
          type: string
        - name: isApproved
          in: path
          required: true
          type: boolean
      responses:
        default:
          description: Error
          schema:
            $ref: "#/definitions/Generic"

  /owners:
    x-swagger-router-controller: owners
    get:
      operationId: getOwners
      responses:
        default:
          description: Error
          schema:
            $ref: "#/definitions/Generic"
    post:
      operationId: addOwner
      parameters:
        - name: owner
          in: body
          required: true
          schema:
            $ref: '#/definitions/Owner'
      responses:
        default:
          description: Error
          schema:
            $ref: "#/definitions/Generic"

  /owners/{ownerId}/approve/{isApproved}:
    x-swagger-router-controller: owners
    get:
      operationId: approveOwner
      parameters:
        - name: ownerId
          in: path
          required: true
          type: string
        - name: isApproved
          in: path
          required: true
          type: boolean
      responses:
        default:
          description: Error
          schema:
            $ref: "#/definitions/Generic"

  /orders:
    x-swagger-router-controller: orders
    get:
      operationId: getOrders
      responses:
        default:
          description: Error
          schema:
            $ref: "#/definitions/Generic"
    post:
      operationId: addOrder
      parameters:
        - name: order
          in: body
          required: true
          schema:
            $ref: '#/definitions/Order'
      responses:
        default:
          description: Error
          schema:
            $ref: "#/definitions/Generic"

  /orders/{orderId}/owner-approve/{isApproved}:
    x-swagger-router-controller: orders
    get:
      operationId: ownerConfirmOrder
      parameters:
        - name: orderId
          in: path
          required: true
          type: string
        - name: isApproved
          in: path
          required: true
          type: boolean
      responses:
        default:
          description: Error
          schema:
            $ref: "#/definitions/Generic"

  /approvals:
    x-swagger-router-controller: approvals
    get:
      operationId: getApprovals
      responses:
        default:
          description: Error
          schema:
            $ref: "#/definitions/Generic"
    post:
      operationId: addApproval
      parameters:
        - name: owner
          in: body
          required: true
          schema:
            $ref: '#/definitions/Approval'
      responses:
        default:
          description: Error
          schema:
            $ref: "#/definitions/Generic"

definitions:
  Generic:
    description: generic

  Order:
    properties:
      resource:
        type: string
      startDate:
        type: number
      endDate:
        type: number
      id:
        type: string
      contractor:
        type: string
      customer:
        type: string
      confirmByOwner:
        type: boolean
      owner:
        type: string

  Approval:
    properties:
      type:
        type: string
      fk:
        type: string
      id:
        type: string
      comments:
        type: string
      contractor:
        type: string
      approved:
        type: boolean

  Owner:
    properties:
      id:
        type: string
      profilePicture:
        type: string
      contact:
        properties:
          idPicture:
            type: string
          id:
            type: string
          name:
            type: string
          phone:
            type: string
          email:
            type: string
          city:
            type: string
          address:
            type: string
      howToContact:
        properties:
          whatsapp:
            type: boolean
          sms:
            type: boolean
          call:
            type: boolean
          email:
            type: boolean
      password:
        type: string
      approved:
        type: boolean

  Resource:
    properties:
      owner:
        type: string
      requirements:
        properties:
          kosher:
            type: boolean
          genders:
            type: array
            items:
              type: string
          languages:
            type: array
            items:
              type: string
          preferences:
            type: string
      pictures:
        type: array
        items:
          type: string
      id:
        type: string
      address:
        type: string
      approved:
        type: boolean
        default: false